"""Token variants that mean the same thing.

Most of this table is learned, not written. Aligning matched records from the
training ground truth and reading off the single-token disagreements ranks the
corpus's corruptions by what they actually cost: road against rd leads at 1024
occurrences, street against st at 966, drive against dr at 955, avenue against
ave at 670 -- each on its own larger than every region abbreviation combined,
and present in nearly every US address.

Clustering those pairs also exposes a second corruption class: digits standing
in for the letters they resemble, as in s0lutions, g1obal and techn0logies,
alongside singular and plural forms of the same word. Within a cluster the
cleanest spelling wins, never the corrupted one -- choosing by length alone
once mapped "best" onto "8est".

The postal and region entries are written out because a table learned from one
sample covers only the variants that sample happened to contain, and the test
set will carry others. Both kinds are spelling knowledge compiled into the
code, in the same spirit as the legal-suffix list the normaliser already
applies: nothing is looked up, no registry or geocoder is consulted, and no
network is reached.
"""

VARIANTS: dict[str, str] = {
    '0fice': 'ofice',
    '5afe': 'safe',
    '5ervices': 'services',
    '5hre': 'shre',
    '5ilver': 'silver',
    '5mith': 'smith',
    '5olutions': 'solutions',
    '5ons': 'sons',
    '5tar': 'star',
    '5upreme': 'supreme',
    '5ystems': 'systems',
    '6lobal': 'global',
    '6olden': 'golden',
    '8est': 'best',
    '8lue': 'blue',
    '8right': 'bright',
    '8rothers': 'brothers',
    'a1l': 'alabama',
    'agr0': 'egro',
    'agro': 'egro',
    'ak': 'alaska',
    'al': 'alabama',
    'ank1e': 'ankle',
    'ap': 'andhra pradesh',
    'apt': 'apartment',
    'ar': 'arkansas',
    'arihnt': 'arihant',
    'as0ciates': 'asociates',
    'asociate': 'asociates',
    'at1antic': 'atlantic',
    'av': 'avenue',
    'ave': 'avenue',
    'aven': 'avenue',
    'az': 'arizona',
    'b1ue': 'blue',
    'bhart': 'bharat',
    'bijnes': 'busines',
    'bildrs': 'builders',
    'bldg': 'building',
    'blk': 'block',
    'blu': 'blue',
    'blv': 'boulevard',
    'blvd': 'boulevard',
    'br': 'bihar',
    'br0thers': 'brothers',
    'brait': 'bright',
    'c0nstruction': 'construction',
    'c0nsultants': 'consultants',
    'c1asic': 'clasic',
    'c1inic': 'clinic',
    'ca': 'california',
    'cae': 'care',
    'capita1': 'capital',
    'cardi0logy': 'cardiology',
    'cardio1ogy': 'cardiology',
    'ce': 'care',
    'center': 'centre',
    'cg': 'chhattisgarh',
    'chd': 'chandigarh',
    'cir': 'circle',
    'circ': 'circle',
    'cnt': 'connecticut',
    'co': 'colorado',
    'consu1tants': 'consultants',
    'continenta1': 'continental',
    'court': 'conecticut',
    'cr': 'care',
    'cre': 'care',
    'crt': 'court',
    'ct': 'court',
    'cust0m': 'custom',
    'cv': 'cove',
    'de': 'delaware',
    'de1hi': 'delhi',
    'denta1': 'dental',
    'devel0pers': 'developers',
    'devlprs': 'developers',
    'digita1': 'digital',
    'dirve': 'drvie',
    'dive': 'drvie',
    'dl': 'delhi',
    'dr': 'drive',
    'drie': 'drvie',
    'drive': 'drvie',
    'drv': 'drive',
    'drve': 'drvie',
    'educati0n': 'education',
    'enterprises': 'entrpraijes',
    'entrpraijej': 'entrpraijes',
    'estet': 'estate',
    'exports': 'eksports',
    'ext': 'extension',
    'f0ods': 'fods',
    'f0undation': 'foundation',
    'fami1y': 'family',
    'federa1': 'federal',
    'fl': 'florida',
    'flr': 'floor',
    'fr0ntier': 'frontier',
    'ft': 'fort',
    'g1obal': 'global',
    'ga': 'georgia',
    'gj': 'gujarat',
    'gl0bal': 'global',
    'globl': 'global',
    'gret': 'great',
    'gujrat': 'gujarat',
    'h0me': 'home',
    'harb0r': 'harbor',
    'haryana': 'hriyana',
    'haspitaliti': 'honspitailiti',
    'hea1th': 'health',
    'heart1and': 'heartland',
    'hi': 'hawaii',
    'hospitality': 'honspitailiti',
    'hp': 'himachal pradesh',
    'hr': 'haryana',
    'hri': 'hari',
    'hspitaliti': 'honspitailiti',
    'hway': 'highway',
    'hwy': 'highway',
    'ia': 'iowa',
    'id': 'idaho',
    'il': 'illinois',
    'impex': 'impeks',
    'india': 'lndia',
    'indian': 'indiyn',
    'indstrij': 'lndustries',
    'indstris': 'lndustries',
    'industries': 'lndustries',
    'industry': 'lndustries',
    'infra': 'inphra',
    'institute': 'lnstitute',
    'internal': 'lnternal',
    'international': 'lnternational',
    'investments': 'lnvestments',
    'it': 'aiti',
    'jct': 'junction',
    'jh': 'jharkhand',
    'jy': 'jay',
    'ka': 'karnataka',
    'kerala': 'keralam',
    'keralam': 'kerala',
    'kerln': 'keralam',
    'keyst0ne': 'keystone',
    'kl': 'kerala',
    'knslting': 'consulting',
    'krnatk': 'karnataka',
    'ks': 'kansas',
    'ky': 'kentucky',
    'l0gistics': 'lonjistiks',
    'l1c': 'lc',
    'la': 'louisiana',
    'lae': 'lane',
    'lksmi': 'lakshmi',
    'ln': 'lane',
    'lne': 'lane',
    'lnfra': 'inphra',
    'logistics': 'lonjistiks',
    'lots': 'lotus',
    'm0untain': 'mountain',
    'ma': 'massachusetts',
    'mainejment': 'management',
    'md': 'maryland',
    'me': 'maine',
    'media': 'midiya',
    'menejment': 'management',
    'metr0': 'metro',
    'mh': 'maharashtra',
    'mharastr': 'maharashtra',
    'mi': 'michigan',
    'mn': 'minnesota',
    'mo': 'missouri',
    'modern': 'mondrn',
    'mount': 'montana',
    'mp': 'madhya pradesh',
    'ms': 'mississippi',
    'mt': 'mount',
    'mtn': 'montana',
    'my': 'may',
    'n0rth': 'north',
    'n0rthern': 'northern',
    'nationa1': 'national',
    'nbr': 'nebraska',
    'nc': 'north carolina',
    'nd': 'north dakota',
    'ne': 'nebraska',
    'nh': 'new hampshire',
    'nj': 'new jersey',
    'nm': 'new mexico',
    'nr': 'near',
    'nv': 'nevada',
    'ny': 'new york',
    'oh': 'ohio',
    'ok': 'oklahoma',
    'opp': 'opposite',
    'or': 'oregon',
    'orisa': 'odisha',
    'orissa': 'odisha',
    'pa': 'pennsylvania',
    'partner': 'partners',
    'pb': 'punjab',
    'physica1': 'physical',
    'pi0ner': 'pioner',
    'piedm0nt': 'piedmont',
    'pkwy': 'parkway',
    'pky': 'parkway',
    'pl': 'place',
    'plz': 'plaza',
    'pnjab': 'punjab',
    'pr0ducer': 'prodyusr',
    'pr0ducts': 'products',
    'pr0jects': 'projekts',
    'pr0perties': 'properties',
    'praim': 'prime',
    'prajekts': 'projekts',
    'prodakts': 'products',
    'prodkts': 'products',
    'producer': 'prodyusr',
    'projects': 'projekts',
    'pronprtij': 'properties',
    'proprtijh': 'properties',
    'pt': 'point',
    'rad': 'roda',
    'rajsthan': 'rajasthan',
    'raod': 'roda',
    'rd': 'road',
    'rea1ty': 'realty',
    'ri': 'rhode island',
    'rj': 'rajasthan',
    'road': 'roda',
    'rod': 'roda',
    'rods': 'road',
    's0ftware': 'software',
    's0lutions': 'solutions',
    's0ns': 'sons',
    'saint': 'stret',
    'sc': 'south carolina',
    'sd': 'south dakota',
    'sec': 'sector',
    'service': 'services',
    'sevn': 'seven',
    'shkti': 'shakti',
    'si1ver': 'silver',
    'silvr': 'silver',
    'sistms': 'systems',
    'sn': 'sun',
    'so1utions': 'solutions',
    'solution': 'solutions',
    'sq': 'square',
    'st': 'street',
    'ste': 'suite',
    'stet': 'stret',
    'str': 'street',
    'stret': 'street',
    'strt': 'street',
    'suprim': 'supreme',
    'svstik': 'swastik',
    'tamilnadu': 'tamil nadu',
    'techn0logies': 'technologies',
    'techn0logy': 'technologies',
    'techno1ogies': 'technologies',
    'technology': 'technologies',
    'telngan': 'telangana',
    'ter': 'terrace',
    'terr': 'terrace',
    'tg': 'telangana',
    'tirupti': 'tirupati',
    'tn': 'tennessee',
    'trading': 'treding',
    'trl': 'trail',
    'ts': 'telangana',
    'tx': 'texas',
    'united': 'yunaited',
    'up': 'uttar pradesh',
    'ut': 'utah',
    'va': 'virginia',
    'vijy': 'vijay',
    'visi0n': 'vision',
    'vt': 'vermont',
    'wa': 'washington',
    'wb': 'west bengal',
    'wi': 'wisconsin',
    'wi1liams': 'wiliams',
    'wv': 'west virginia',
    'wy': 'wyoming',
}
