"""Token variants that mean the same thing.

Most of this table is learned, not written. Aligning matched records from the
training ground truth and reading off the single-token disagreements ranks the
corpus's corruptions by what they cost: road against rd leads at 1024
occurrences, street against st at 966, drive against dr at 955, avenue against
ave at 670. Clustering those pairs also exposes digits standing in for the
letters they resemble, as in s0lutions and techn0logies, and singular against
plural forms.

Short keys are held separately because a two-letter code means different things
in different languages. Applied everywhere, this table rewrote French
addresses into nonsense: "rue de la Paix" became "rue delaware louisiana paix"
and "Saint-Nazaire" became "street nazaire", because de, la and st are a US
state, a US state and an English street type as well as the three commonest
words in a French address. The training data covers only US and India, so
every short mapping here was learned or written for those two, and SHORT is
applied only to them. Anything longer is a spelling correction rather than an
abbreviation and carries no such ambiguity, so GLOBAL applies everywhere.

The rule is on the length, not on a list of exceptions, because the next
country the organisers add will collide with a different set of two-letter
codes than French does.
"""

# Deliberately absent: court->conecticut, mount->montana, saint->stret.
# Clustering produced all three because the abbreviation is genuinely
# ambiguous in English -- ct is Court and Connecticut, mt is Mount and
# Montana, st is Saint and Street -- so the long forms were merged through
# the shared short one. Unlike a misspelling, these join two different words,
# and they corrupt every country: "123 Oak Court" became "123 oak
# conecticut". A cluster whose members are both clean words that are not
# similar to each other is a merge, not a variant.

GLOBAL: dict[str, str] = {
    '0fice': 'ofice',
    '5afe': 'safe',
    '5ervices': 'services',
    '5hre': 'shre',
    '5ilver': 'silver',
    '5mith': 'smith',
    '5olutions': 'solutions',
    '5ons': 'sons',
    '5tar': 'star',
    '5upreme': 'supreme',
    '5ystems': 'systems',
    '6lobal': 'global',
    '6olden': 'golden',
    '8est': 'best',
    '8lue': 'blue',
    '8right': 'bright',
    '8rothers': 'brothers',
    'agr0': 'egro',
    'agro': 'egro',
    'ank1e': 'ankle',
    'arihnt': 'arihant',
    'as0ciates': 'asociates',
    'asociate': 'asociates',
    'at1antic': 'atlantic',
    'aven': 'avenue',
    'b1ue': 'blue',
    'bhart': 'bharat',
    'bijnes': 'busines',
    'bildrs': 'builders',
    'bldg': 'building',
    'blvd': 'boulevard',
    'br0thers': 'brothers',
    'brait': 'bright',
    'c0nstruction': 'construction',
    'c0nsultants': 'consultants',
    'c1asic': 'clasic',
    'c1inic': 'clinic',
    'capita1': 'capital',
    'cardi0logy': 'cardiology',
    'cardio1ogy': 'cardiology',
    'center': 'centre',
    'circ': 'circle',
    'consu1tants': 'consultants',
    'continenta1': 'continental',
    'cust0m': 'custom',
    'de1hi': 'delhi',
    'denta1': 'dental',
    'devel0pers': 'developers',
    'devlprs': 'developers',
    'digita1': 'digital',
    'dirve': 'drvie',
    'dive': 'drvie',
    'drie': 'drvie',
    'drive': 'drvie',
    'drve': 'drvie',
    'educati0n': 'education',
    'enterprises': 'entrpraijes',
    'entrpraijej': 'entrpraijes',
    'estet': 'estate',
    'exports': 'eksports',
    'f0ods': 'fods',
    'f0undation': 'foundation',
    'fami1y': 'family',
    'federa1': 'federal',
    'fr0ntier': 'frontier',
    'g1obal': 'global',
    'gl0bal': 'global',
    'globl': 'global',
    'gret': 'great',
    'gujrat': 'gujarat',
    'h0me': 'home',
    'harb0r': 'harbor',
    'haryana': 'hriyana',
    'haspitaliti': 'honspitailiti',
    'hea1th': 'health',
    'heart1and': 'heartland',
    'hospitality': 'honspitailiti',
    'hspitaliti': 'honspitailiti',
    'hway': 'highway',
    'impex': 'impeks',
    'india': 'lndia',
    'indian': 'indiyn',
    'indstrij': 'lndustries',
    'indstris': 'lndustries',
    'industries': 'lndustries',
    'industry': 'lndustries',
    'infra': 'inphra',
    'institute': 'lnstitute',
    'internal': 'lnternal',
    'international': 'lnternational',
    'investments': 'lnvestments',
    'kerala': 'keralam',
    'keralam': 'kerala',
    'kerln': 'keralam',
    'keyst0ne': 'keystone',
    'knslting': 'consulting',
    'krnatk': 'karnataka',
    'l0gistics': 'lonjistiks',
    'lksmi': 'lakshmi',
    'lnfra': 'inphra',
    'logistics': 'lonjistiks',
    'lots': 'lotus',
    'm0untain': 'mountain',
    'mainejment': 'management',
    'media': 'midiya',
    'menejment': 'management',
    'metr0': 'metro',
    'mharastr': 'maharashtra',
    'modern': 'mondrn',
    'n0rth': 'north',
    'n0rthern': 'northern',
    'nationa1': 'national',
    'orisa': 'odisha',
    'orissa': 'odisha',
    'partner': 'partners',
    'physica1': 'physical',
    'pi0ner': 'pioner',
    'piedm0nt': 'piedmont',
    'pkwy': 'parkway',
    'pnjab': 'punjab',
    'pr0ducer': 'prodyusr',
    'pr0ducts': 'products',
    'pr0jects': 'projekts',
    'pr0perties': 'properties',
    'praim': 'prime',
    'prajekts': 'projekts',
    'prodakts': 'products',
    'prodkts': 'products',
    'producer': 'prodyusr',
    'projects': 'projekts',
    'pronprtij': 'properties',
    'proprtijh': 'properties',
    'rajsthan': 'rajasthan',
    'raod': 'roda',
    'rea1ty': 'realty',
    'road': 'roda',
    'rods': 'road',
    's0ftware': 'software',
    's0lutions': 'solutions',
    's0ns': 'sons',
    'service': 'services',
    'sevn': 'seven',
    'shkti': 'shakti',
    'si1ver': 'silver',
    'silvr': 'silver',
    'sistms': 'systems',
    'so1utions': 'solutions',
    'solution': 'solutions',
    'stet': 'stret',
    'stret': 'street',
    'strt': 'street',
    'suprim': 'supreme',
    'svstik': 'swastik',
    'tamilnadu': 'tamil nadu',
    'techn0logies': 'technologies',
    'techn0logy': 'technologies',
    'techno1ogies': 'technologies',
    'technology': 'technologies',
    'telngan': 'telangana',
    'terr': 'terrace',
    'tirupti': 'tirupati',
    'trading': 'treding',
    'united': 'yunaited',
    'vijy': 'vijay',
    'visi0n': 'vision',
    'wi1liams': 'wiliams',
}

# Applied only to records from countries these were derived from.
SHORT_COUNTRIES = frozenset({"US", "India"})

SHORT: dict[str, str] = {
    'a1l': 'alabama',
    'ak': 'alaska',
    'al': 'alabama',
    'ap': 'andhra pradesh',
    'apt': 'apartment',
    'ar': 'arkansas',
    'av': 'avenue',
    'ave': 'avenue',
    'az': 'arizona',
    'blk': 'block',
    'blu': 'blue',
    'blv': 'boulevard',
    'br': 'bihar',
    'ca': 'california',
    'cae': 'care',
    'ce': 'care',
    'cg': 'chhattisgarh',
    'chd': 'chandigarh',
    'cir': 'circle',
    'cnt': 'connecticut',
    'co': 'colorado',
    'cr': 'care',
    'cre': 'care',
    'crt': 'court',
    'ct': 'court',
    'cv': 'cove',
    'de': 'delaware',
    'dl': 'delhi',
    'dr': 'drive',
    'drv': 'drive',
    'ext': 'extension',
    'fl': 'florida',
    'flr': 'floor',
    'ft': 'fort',
    'ga': 'georgia',
    'gj': 'gujarat',
    'hi': 'hawaii',
    'hp': 'himachal pradesh',
    'hr': 'haryana',
    'hri': 'hari',
    'hwy': 'highway',
    'ia': 'iowa',
    'id': 'idaho',
    'il': 'illinois',
    'it': 'aiti',
    'jct': 'junction',
    'jh': 'jharkhand',
    'jy': 'jay',
    'ka': 'karnataka',
    'kl': 'kerala',
    'ks': 'kansas',
    'ky': 'kentucky',
    'l1c': 'lc',
    'la': 'louisiana',
    'lae': 'lane',
    'ln': 'lane',
    'lne': 'lane',
    'ma': 'massachusetts',
    'md': 'maryland',
    'me': 'maine',
    'mh': 'maharashtra',
    'mi': 'michigan',
    'mn': 'minnesota',
    'mo': 'missouri',
    'mp': 'madhya pradesh',
    'ms': 'mississippi',
    'mt': 'mount',
    'mtn': 'montana',
    'my': 'may',
    'nbr': 'nebraska',
    'nc': 'north carolina',
    'nd': 'north dakota',
    'ne': 'nebraska',
    'nh': 'new hampshire',
    'nj': 'new jersey',
    'nm': 'new mexico',
    'nr': 'near',
    'nv': 'nevada',
    'ny': 'new york',
    'oh': 'ohio',
    'ok': 'oklahoma',
    'opp': 'opposite',
    'or': 'oregon',
    'pa': 'pennsylvania',
    'pb': 'punjab',
    'pky': 'parkway',
    'pl': 'place',
    'plz': 'plaza',
    'pt': 'point',
    'rad': 'roda',
    'rd': 'road',
    'ri': 'rhode island',
    'rj': 'rajasthan',
    'rod': 'roda',
    'sc': 'south carolina',
    'sd': 'south dakota',
    'sec': 'sector',
    'sn': 'sun',
    'sq': 'square',
    'st': 'street',
    'ste': 'suite',
    'str': 'street',
    'ter': 'terrace',
    'tg': 'telangana',
    'tn': 'tennessee',
    'trl': 'trail',
    'ts': 'telangana',
    'tx': 'texas',
    'up': 'uttar pradesh',
    'ut': 'utah',
    'va': 'virginia',
    'vt': 'vermont',
    'wa': 'washington',
    'wb': 'west bengal',
    'wi': 'wisconsin',
    'wv': 'west virginia',
    'wy': 'wyoming',
}

# Kept for callers that want everything, e.g. analysing the table itself.
VARIANTS = {**GLOBAL, **SHORT}
